[server]
name = "item-search"
contextPath = "/item/search"
port = 8080
runMode = "debug"
readTimeOut = 1000
writeTimeOut = 1000

[elastic]
protocol = "http"
host = "127.0.0.1"
port = 9200
username = "elastic"
password = "123456"
index = "search_index"

[redis]
host = "127.0.0.1"
port = 6379
password = "123456"
db = 0

[mysql]
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"
database = "common"